### ISSUE TITLE
Need help: Broken CSS for the tool

### ISSUE THREAD

**Issue by yodhavee** [algolia/tools#22]
After setup and run. The page CSS are broken. Please see the screenshot

Tool compiled successfully
<img src="https://user-images.githubusercontent.com/24387163/114354358-50ed5f00-9b98-11eb-8955-80c88e16accf.png" width=400>

However, when opening the tool. All the CSS seems to be broken
<img src="https://user-images.githubusercontent.com/24387163/114354541-91e57380-9b98-11eb-8981-9c3560163935.png" width=400>

Some info in case it helps

<img src="https://user-images.githubusercontent.com/24387163/114400660-62e8f500-9bcc-11eb-9de6-73508ab18066.png" width=400>
<img src="https://user-images.githubusercontent.com/24387163/114400676-68463f80-9bcc-11eb-8bd6-c33ca4937bc2.png" width=400>

Please let me know if you need further clarification. Thank you.

**Comment by bobbygroves1** [comment]
Hi @maxiloc , hope all is well with you!

@julienpa mentioned to @ you here as an FYI to the issue. I also repro'd the issue on my side and saw the same UI issue with the CSS.

**Comment by maxiloc** [comment]
Hey both, sorry I didn't receive notif for this.
I just create a pr to update the readme with how to fix this: https://github.com/algolia/tools/pull/25/files
Just make sure you apply the change from the PR first https://github.com/algolia/tools/pull/24/files

Let me know if that fixes it.

**Comment by maxiloc** [comment]
Closing this as this should be fixed
